### PR TITLE
link flags

### PR DESCRIPTION
**Pull request by will**
This would (maybe) address the issues in https://github.com/will/crystal-pg/issues/14 due to https://github.com/manastech/crystal/issues/1269 however because of https://github.com/manastech/omnibus-crystal/issues/2 it doesn't work right now.

### CODE REVIEW

**Comment by zamith** [comment]
@will That's a lot of libraries being linked, tbh. Just let me know when this works and I'll merge it in. ;)

**Comment by will** [comment]
Yeah, well it's just making explicit what is linking anyway. It probably doesn't have to be hardcoded, and instead from looking through what's in the /embedded dir.

I don't really know much about the linker, but I hope that it can be fixed in crystal itself rather than need to do this long-term. But I really don't know :/

**Comment by zamith** [comment]
Does that mean we just have to wait, or merging it in as is will help?

**Comment by will** [comment]
We need to at least wait until the tgz has the broken symlink fixed https://github.com/manastech/omnibus-crystal/issues/2

**Comment by kbrock** [comment]
would settind `LD_LIBRARY_PATH` fix this issue, or do those libraries need to be explicitly included?

**Comment by will** [comment]
from @fdr and my investigation, once /usr/lib is included at all, everything goes to hell, unless all the other crystal/embedded/lib libs are explicitly included :/

**Comment by zamith** [comment]
@will Any luck with this?

**Comment by will** [comment]
No, I was hoping that they'd fix the linking thing in the main crystal project with manastech/crystal#1269 , but it seems like the current main focus over there is rewriting the compiler, so it may be a while before they get to that. 

In the mean time, there are maybe some hack work arounds. This is really gross, but maybe it'd work, in the buildpack:
- copy the libpq library file (probably just the one file?) to a different directory
- make an executable script that is called pg_config that lies and says the libdir is that new directory, and put that earlier in $PATH
- maybe that works?

:/

**Comment by zamith** [comment]
@will You're welcome to do as you please. I got back to this because I need to add support for the new dependency management system in Crystal, so I'm going through the PRs.

We can try that hack, or wait for the long term fix, I leave it up to you because this is a bit out of my comfort zone.

**Comment by zamith** [comment]
@will Is it ok for me to close this, or is this moving forward in any way? Thanks.

**Comment by will** [comment]
It doesn't look like it's moving forward. I also recently started working on a native crystal implementation which won't require linking libpq

**Pull request closed without merging**
